version: '3'

services:
  # see https://github.com/PowerDNS/pdns/blob/master/Docker-README.md
  recursor: # The server to either recurse to public DNS servers or to our own authoritative on for private domains
    image: powerdns/pdns-recursor-45:latest
    restart: always
    volumes:
      - ./recursor/recursor.conf:/etc/powerdns/recursor.conf
      - ./recursor/custom.d/toauth.conf:/etc/powerdns/recursor.d/toauth.conf
    environment:
      - PDNS_RECURSOR_API_KEY
    ports:
      - '${DNS_PORT:-53}:53'
      - '${DNS_PORT:-53}:53/udp'
    depends_on:
      - auth
    networks:
      - recursor
  auth: # the server to store our private DNS entries
    image: powerdns/pdns-auth-45:latest
    restart: always
    networks:
      recursor:
        ipv4_address: ${NETWORK:-172.21.0}.226
    volumes:
      - dns-data:/var/lib/powerdns/
    environment:
      - PDNS_AUTH_API_KEY

volumes:
  # dns zone data
  dns-data:

networks:
  recursor:
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK:-172.21.0}.225/29
          gateway: ${NETWORK:-172.21.0}.225
