version: '3'

services:
  gui:
    labels:
      traefik.http.routers.gui.tls: 'false'
    ports:
      - 10080:80
  auth:
    ports:
      #- 3053:53
      - '3053:53/udp'
  recursor:
    ports:
      - '4053:53/tcp'
      - '4053:53/udp'
