version: '3'

services:
  # see https://github.com/PowerDNS/pdns/blob/master/Docker-README.md
  recursor: # The server to either recurse to public DNS servers or to our own authoritative on for private domains
    image: powerdns/pdns-recursor-45:latest
    restart: always
    environment:
      - PDNS_RECURSOR_API_KEY
    depends_on:
      - auth
  auth: # the server to store our private DNS entries
    image: powerdns/pdns-auth-45:latest
    restart: always
    volumes:
      - dns-data:/var/lib/powerdns/
    environment:
      - PDNS_AUTH_API_KEY
  dnsdist:
    image: powerdns/dnsdist-17:latest
    restart: always
    ports:
      - '${DNS_PORT:-53}:53'
      - '${DNS_PORT:-53}:53/udp'
    environment:
      - PDNS_AUTH_API_KEY
    volumes:
      - ./dnsdist/01_resolv.conf:/etc/dnsdist/conf.d/01_resolv.conf
      - ./dnsdist/custom.d/02_private_domain.conf:/etc/dnsdist/conf.d/02_private_domain.conf
      - ./dnsdist/99_recursor.conf:/etc/dnsdist/conf.d/99_recursor.conf
    depends_on:
      - auth
      - recursor
volumes:
  # dns zone data
  dns-data:
